url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Coalition for Empowerment and Opportunity
email: your-email@domain.com
description: "The Coalition for Empowerment and Opportunity is dedicated to disrupting the structures of oppression that impact youth and young adults of color."


# Team names, titles and social links
people:
- name: Marguarite Gooden
  pic: 1
  position: Board Member
  description: Marguerite is a retired Arlington Public Schools Principal. Native resident of Halls Hill and a community activist!
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Matt Rogers
  pic: 2
  position: Board Member
  description: Matt is the Chief of Staff to Loudoun County Chair At-Large Phyllis J. Randall. A native of Philadelphia, PA and alumnus of Virginia Commonwealth University in Richmond, VA, Matt came to the Chair’s office in 2021 after 4.5 consecutive years of working around the Virginia General Assembly – 3.5 of those most recent years as the Chief of Staff to a Virginia State Senator. In 2021, Matt was himself a candidate for the old Virginia House of Delegates’ 47th district in Arlington, VA. In his limited spare time, Matt is the Board President of WERA 96.7 in Arlington, VA and the host of a sports podcast named “Honorable Mention” frequented by famous voices from ESPN, NBC, CBS, Sports Radio 94WIP, and others. He now lives in Loudoun County, VA with his wife, Jasmine, and his son, Mandela.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Quimari Mullins
  pic: 3
  position: Board Member
  description: Quimari is a 25 year old Arlington native whose mission is to be a light and resource in the lives of youth in her community. Currently she teaches Pre-Kindergarten in a private school in Arlington. Growing up in a turbulent environment propelled her into what she hopes will be a lifetime of service. 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Zak Mahshie
  pic: 3
  position: Board Member
  description: Zak is General Counsel and co-owner of Excella, Inc., a technology services company bringing innovation to private and public sector clients. Through Excella’s ImpaX program, Zak has been active in supporting organizations targeting the root causes of homelessness.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Zakiya Worthey
  pic: 3
  position: Board Member
  description: Zakiya is the CEO of K. Lamb, a human-centered consulting firm that provides strategic business planning, workplace culture and organizational consulting, diversity, equity, inclusion and belonging competencies, and change management best practices and techniques. She is also active in the community, serving on multiple non-profit boards and is the Commissioner of the NoVA Juvenile Detention Center Commission.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty